# Generated by Django 3.2.25 on 2024-07-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='device_images/'),
        ),
        migrations.AddField(
            model_name='device',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='device_images/'),
        ),
        migrations.AddField(
            model_name='device',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='device_images/'),
        ),
        migrations.AddField(
            model_name='device',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('negotiable', 'Negotiable')], default='fixed', max_length=10),
        ),
    ]
