# Generated by Django 3.2.25 on 2024-07-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_itemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='store.itemcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=20),
        ),
    ]
