# Generated by Django 3.2.25 on 2024-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20240720_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('New', 'New'), ('New', 'Used'), ('Refurbished', 'Refurbished')], default='New', max_length=20),
        ),
    ]
