# Generated by Django 5.2.1 on 2026-03-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_admin_notes_order_deposit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calculated_total_percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(choices=[('less_than_1_day', 'Less than 1 day'), ('2_to_3_days', '2 to 3 days'), ('7_days', '7 days'), ('14_days', '14 days'), ('1_month', '1 month'), ('more_than_1_month', '>1 month')], default='2_to_3_days', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
