# Generated by Django 5.2.1 on 2026-03-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_calculated_total_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(choices=[('less_than_1_day', 'Less than 1 day (Urgent)'), ('2_to_3_days', '2 to 3 days'), ('7_days', '7 days'), ('14_days', '14 days'), ('1_month', '1 month'), ('more_than_1_month', '>1 month')], default='2_to_3_days', max_length=30),
        ),
    ]
