# Generated by Django 5.2.1 on 2026-04-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_base_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AddField(
            model_name='device',
            name='page',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=20),
        ),
    ]
