# Generated by Django 6.0.3 on 2026-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_device_options_device_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('gray', 'Gray'), ('navy', 'Navy'), ('brown', 'Brown'), ('custom', 'Custom Color')], default='black', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gender',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('women', 'Women'), ('young', 'Young'), ('child', 'Child'), ('unisex', 'Unisex')], default='adult', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', 'Double XL'), ('3XL', 'Triple XL'), ('4XL', 'Quadruple XL'), ('custom', 'Custom Size')], default='M', max_length=10, null=True),
        ),
    ]
