# Generated by Django 5.2.1 on 2026-04-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_alter_itemprice_day_shift'),
        ('store', '0021_order_color_order_gender_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='setups.itemcategory'),
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
