# Generated by Django 5.2.1 on 2026-04-23 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_alter_itemprice_day_shift'),
        ('store', '0022_alter_device_category_delete_itemcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='setups.itemtype'),
        ),
    ]
