# Generated by Django 5.2.1 on 2026-04-23 13:44

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0005_itemtype_id_alter_itemtype_name'),
        ('store', '0023_alter_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='setups.itemtype'),
        ),
    ]
