# Generated by Django 5.2.1 on 2026-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
        migrations.AddField(
            model_name='device',
            name='front',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
    ]
