# Generated by Django 5.2.1 on 2026-05-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_device_back_device_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='back',
        ),
        migrations.RemoveField(
            model_name='device',
            name='front',
        ),
    ]
