# Generated by Django 5.2.1 on 2026-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_device_back_remove_device_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='front',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
    ]
