# Generated by Django 5.2.1 on 2026-06-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_news_image_news_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='item_status',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=25),
        ),
    ]
