# Generated by Django 5.2.1 on 2026-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_device_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/'),
        ),
    ]
