# Generated by Django 5.2.1 on 2026-07-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_device_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='item_status',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('service', 'service')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='device',
            name='page',
            field=models.CharField(choices=[('MATERIAL', 'Printing Material'), ('CLOTHING', 'Clothing'), ('SERVICE', 'Services')], max_length=20),
        ),
    ]
