# Generated by Django 5.2.1 on 2026-07-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_device_item_status_alter_device_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sample_design',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
    ]
