# Generated by Django 5.2.1 on 2026-07-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_size_height',
            field=models.CharField(blank=True, help_text='በሜትር/in meter', max_length=10, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_size_width',
            field=models.CharField(blank=True, help_text='በሜትር/in meter', max_length=10, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('women', 'Women'), ('young', 'Young'), ('child', 'Child'), ('kids', 'kids'), ('other', 'other')], default='adult', max_length=20, null=True, verbose_name='Fit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', 'Double XL'), ('3XL', 'Triple XL'), ('4XL', 'Quadruple XL'), ('custom', 'Custom Size'), ('other', 'Other')], default='M', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('service', 'Service'), ('other', 'Other')], default='new', max_length=20),
        ),
    ]
