# Generated by Django 5.2.1 on 2026-07-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_order_service_size_height_order_service_size_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='shipping_fee',
            field=models.CharField(default='Negotiable', max_length=21),
        ),
    ]
