# Generated by Django 5.2.1 on 2026-07-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_device_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
