# Generated by Django 5.2.1 on 2026-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_device_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_size',
            field=models.CharField(blank=True, help_text='ሜትር ስኩየር', max_length=10, null=True, verbose_name='Width x Height'),
        ),
        migrations.AlterField(
            model_name='device',
            name='item_status',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('service', 'Service'), ('other', 'Other')], default='new', max_length=25),
        ),
    ]
