# Generated by Django 5.2.1 on 2026-08-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_order_service_size_alter_device_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(blank=True, choices=[('kids', 'kids'), ('male', 'Male'), ('female', 'Female'), ('other', 'other')], default='adult', max_length=20, null=True, verbose_name='Fit'),
        ),
    ]
