# Generated by Django 5.2.1 on 2026-08-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
    ]
