# Generated by Django 5.2.1 on 2026-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='Day_shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], default='Morning', max_length=250),
        ),
    ]
