# Generated by Django 5.2.1 on 2026-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_alter_itemprice_day_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
