# Generated by Django 5.2.1 on 2026-04-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0003_itemcategory_id_measurement_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPrice',
        ),
    ]
