# Generated by Django 5.2.1 on 2026-04-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0004_delete_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
