# Generated by Django 5.2.1 on 2026-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0005_itemtype_id_alter_itemtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
