# Generated by Django 5.2.1 on 2026-06-16 02:37

import django.core.validators
import setups.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0006_alter_itemtype_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('tier', models.CharField(choices=[('SILVER', 'Silver Tier'), ('GOLD', 'Gold Tier'), ('PLATINUM', 'Platinum Tier')], default='SILVER', max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/%Y/%m/', validators=[setups.models.validate_logo_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])])),
                ('website', models.URLField(blank=True)),
                ('extra_metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSON for custom partner configurations.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corporate Partner',
                'verbose_name_plural': 'Corporate Partners',
                'ordering': ['-tier', 'name'],
            },
        ),
    ]
