# Generated by Django 5.2.1 on 2026-06-16 02:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0007_partner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='partner',
            name='extra_metadata',
        ),
    ]
