# Generated by Django 5.2.1 on 2026-06-21 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0008_alter_partner_managers_remove_partner_extra_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='e.g., Flash Sale! 20% off everything!', max_length=255)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Master switch to turn this off manually.')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the announcement should start showing.')),
                ('end_date', models.DateTimeField(help_text='When the announcement should automatically disappear.')),
            ],
        ),
    ]
