# Generated by Django 5.2.1 on 2026-08-08 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0010_shippingmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementbar',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='announcementbar',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the announcement should automatically disappear.'),
        ),
    ]
