# Generated by Django 5.2.1 on 2026-06-12 21:47

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0006_alter_itemtype_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Day_shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=250)),
                ('Quantity', models.PositiveIntegerField()),
                ('Purchased_single_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Purchased_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('Remark', models.CharField(blank=True, max_length=250, null=True)),
                ('Created_date', models.DateField(auto_now=True)),
                ('Modified_date', models.DateTimeField(auto_now=True)),
                ('Created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.itemcategory')),
                ('Item_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Item_category', chained_model_field='Item_category', on_delete=django.db.models.deletion.CASCADE, to='setups.itemtype')),
                ('Measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.measurement')),
                ('Modified_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Begin inventories',
            },
        ),
        migrations.CreateModel(
            name='PurchasedInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Day_shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=250)),
                ('Quantity', models.PositiveIntegerField()),
                ('Purchased_single_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Purchased_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('Remark', models.CharField(blank=True, max_length=250, null=True)),
                ('Created_date', models.DateField(auto_now=True)),
                ('Modified_date', models.DateTimeField(auto_now=True)),
                ('Created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.itemcategory')),
                ('Item_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Item_category', chained_model_field='Item_category', on_delete=django.db.models.deletion.CASCADE, to='setups.itemtype')),
                ('Measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.measurement')),
                ('Modified_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_byp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Purchased inventories',
            },
        ),
        migrations.CreateModel(
            name='ShahuraBeginInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Day_shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=250)),
                ('Quantity', models.PositiveIntegerField()),
                ('Purchased_single_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Purchased_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('Remark', models.CharField(blank=True, max_length=250, null=True)),
                ('Created_date', models.DateField(auto_now=True)),
                ('Modified_date', models.DateTimeField(auto_now=True)),
                ('Created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.itemcategory')),
                ('Item_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Item_category', chained_model_field='Item_category', on_delete=django.db.models.deletion.CASCADE, to='setups.itemtype')),
                ('Measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.measurement')),
                ('Modified_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_y1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shahura begin inventories',
            },
        ),
        migrations.CreateModel(
            name='ShahuraPurchasedInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Day_shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=250)),
                ('Quantity', models.PositiveIntegerField()),
                ('Purchased_single_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Purchased_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('Remark', models.CharField(blank=True, max_length=250, null=True)),
                ('Created_date', models.DateField(auto_now=True)),
                ('Modified_date', models.DateTimeField(auto_now=True)),
                ('Created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.itemcategory')),
                ('Item_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Item_category', chained_model_field='Item_category', on_delete=django.db.models.deletion.CASCADE, to='setups.itemtype')),
                ('Measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.measurement')),
                ('Modified_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_bp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shahura purchased inventories',
            },
        ),
    ]
