# Generated by Django 5.2.1 on 2026-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shahurabegininventory',
            name='Purchased_single_price',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
