# Generated by Django 5.2.1 on 2026-06-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_shahurabegininventory_purchased_single_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shahurapurchasedinventory',
            name='Created_by',
        ),
        migrations.RemoveField(
            model_name='shahurapurchasedinventory',
            name='Item_category',
        ),
        migrations.RemoveField(
            model_name='shahurapurchasedinventory',
            name='Item_type',
        ),
        migrations.RemoveField(
            model_name='shahurapurchasedinventory',
            name='Measurement',
        ),
        migrations.RemoveField(
            model_name='shahurapurchasedinventory',
            name='Modified_by',
        ),
        migrations.AlterField(
            model_name='begininventory',
            name='Purchased_single_price',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='purchasedinventory',
            name='Purchased_single_price',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.DeleteModel(
            name='ShahuraBeginInventory',
        ),
        migrations.DeleteModel(
            name='ShahuraPurchasedInventory',
        ),
    ]
