# Generated by Django 5.2.1 on 2026-04-23 10:48

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Customer_name', models.CharField(max_length=250)),
                ('Customer_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('Day_shift', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=250, null=True)),
                ('Order_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Delivered', 'Delivered')], max_length=250, null=True)),
                ('Payment_plan', models.CharField(blank=True, choices=[('1', 'Partial'), ('0', 'Full')], max_length=250, null=True)),
                ('Item_total_price', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=11, null=True)),
                ('Price_paid', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=11, null=True)),
                ('The_rest', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=11, null=True)),
                ('Appointment_date', models.DateField(blank=True, null=True)),
                ('Ordered_date', models.DateField(auto_now=True)),
                ('Modified_date', models.DateTimeField(auto_now=True)),
                ('Modified_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Modified_by', to=settings.AUTH_USER_MODEL)),
                ('Ordered_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternalOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Customer_name', models.CharField(max_length=250)),
                ('Customer_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('Day_shift', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=250, null=True)),
                ('Order_source', models.CharField(default='Photo Gate', max_length=250)),
                ('Order_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Delivered', 'Delivered')], max_length=250, null=True)),
                ('Payment_plan', models.CharField(blank=True, choices=[('Partial', 'Partial'), ('Full', 'Full')], max_length=250, null=True)),
                ('Item_total_price', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=11, null=True)),
                ('Price_paid', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=11, null=True)),
                ('The_rest', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=11, null=True)),
                ('Apointment_date', models.DateField(blank=True, null=True)),
                ('Ordered_date', models.DateField(auto_now=True)),
                ('Modified_date', models.DateTimeField(auto_now=True)),
                ('Modified_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
                ('Ordered_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewExternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_severity', models.CharField(choices=[('Regular', 'Regular'), ('Urgent', 'Urgent')], max_length=250)),
                ('Photo_is', models.CharField(choices=[('Edited', 'Edited'), ('Not Edited', 'Not Edited')], max_length=250)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Single_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('External_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.externalorder')),
                ('Item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.itemcategory')),
                ('Item_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Item_category', chained_model_field='Item_category', on_delete=django.db.models.deletion.CASCADE, to='setups.itemtype')),
            ],
            options={
                'verbose_name': 'New external order',
                'verbose_name_plural': 'New external orders',
            },
        ),
        migrations.CreateModel(
            name='NewInternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_severity', models.CharField(choices=[('Regular', 'Regular'), ('Urgent', 'Urgent')], max_length=250)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Single_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('Internal_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.internalorder')),
                ('Item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.itemcategory')),
                ('Item_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Item_category', chained_model_field='Item_category', on_delete=django.db.models.deletion.CASCADE, to='setups.itemtype')),
            ],
            options={
                'verbose_name': 'New internal order',
                'verbose_name_plural': 'New internal orders',
            },
        ),
    ]
