# Generated by Django 5.2.1 on 2026-04-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalorder',
            old_name='Apointment_date',
            new_name='Appointment_date',
        ),
    ]
