# Generated by Django 5.2.1 on 2026-04-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_apointment_date_internalorder_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalorder',
            name='Order_source',
            field=models.CharField(default='Online', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='Order_source',
            field=models.CharField(default='Parrot Advert', editable=False, max_length=250),
        ),
    ]
