# Generated by Django 5.2.1 on 2026-04-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_externalorder_order_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorder',
            name='Day_shift',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], default='Morning', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='externalorder',
            name='Order_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Delivered', 'Delivered')], default='Pending', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='externalorder',
            name='Payment_plan',
            field=models.CharField(blank=True, choices=[('1', 'Partial'), ('0', 'Full')], default='Full', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='Day_shift',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], default='Morning', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='Order_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Delivered', 'Delivered')], default='Pending', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='Payment_plan',
            field=models.CharField(blank=True, choices=[('Partial', 'Partial'), ('Full', 'Full')], default='Full', max_length=250, null=True),
        ),
    ]
