# Generated by Django 5.2.1 on 2026-04-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_externalorder_day_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorder',
            name='Payment_plan',
            field=models.CharField(blank=True, choices=[('Partial', 'Partial'), ('Full', 'Full')], default='Full', max_length=250, null=True),
        ),
    ]
