# Generated by Django 5.2.1 on 2026-04-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_externalorder_payment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newexternalorder',
            name='Photo_is',
        ),
    ]
