# Generated by Django 5.2.1 on 2026-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_newexternalorder_photo_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorder',
            name='Order_source',
            field=models.CharField(default='Online', max_length=250),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='Order_source',
            field=models.CharField(default='Parrot Advert', max_length=250),
        ),
    ]
