# Generated by Django 5.2.1 on 2026-04-24 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_externalorder_order_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newexternalorder',
            name='Photo_is',
            field=models.CharField(blank=True, choices=[('Edited', 'Edited'), ('Not Edited', 'Not Edited')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='externalorder',
            name='Modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_orders_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externalorder',
            name='Ordered_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_orders_ordered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='Modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_orders_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='Ordered_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_orders_ordered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newexternalorder',
            name='External_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.externalorder'),
        ),
        migrations.AlterField(
            model_name='newexternalorder',
            name='Single_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='newinternalorder',
            name='Internal_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.internalorder'),
        ),
        migrations.AlterField(
            model_name='newinternalorder',
            name='Single_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
