# Generated by Django 5.2.1 on 2026-04-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_newexternalorder_photo_is_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newexternalorder',
            name='Photo_is',
        ),
    ]
