# Generated by Django 5.2.1 on 2026-04-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_newexternalorder_photo_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newexternalorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
