# Generated by Django 5.2.1 on 2026-04-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_newexternalorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinternalorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
