# Generated by Django 5.2.1 on 2026-04-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_newsale_sale_single_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='Day_shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], default='Morning', max_length=250),
        ),
    ]
